Repository 21Enzo17/asist.io, pull requests merged in 2024-03, with the labels that each got.

#15 Feature/seguridad
  Asist.swagger.json
  output.log
  pom.xml
  src/main/java/asist/io/Application.java
  src/main/java/asist/io/auth/JwtAuthorizationFilter.java
  src/main/java/asist/io/auth/JwtUtil.java
  src/main/java/asist/io/auth/SecurityConfig.java
  src/main/java/asist/io/controller/AuthController.java
  src/main/java/asist/io/controller/UsuarioController.java
  src/main/java/asist/io/dto/usuarioDtos/UsuarioDto.java
  src/main/java/asist/io/dto/usuarioDtos/UsuarioLoginDto.java
  src/main/java/asist/io/dto/usuarioDtos/UsuarioLoginResDto.java
  src/main/java/asist/io/dto/usuarioDtos/UsuarioRegDto.java
  src/main/java/asist/io/entity/Curso.java
  src/main/java/asist/io/entity/Token.java
  src/main/java/asist/io/entity/Usuario.java
  src/main/java/asist/io/enums/TipoToken.java
  src/main/java/asist/io/exception/ModelException.java
  src/main/java/asist/io/handler/GlobalExceptionHandler.java
  src/main/java/asist/io/handler/ValidationError.java
  src/main/java/asist/io/mapper/UsuarioMapper.java
  src/main/java/asist/io/repository/TokenRepository.java
  src/main/java/asist/io/repository/UsuarioRepository.java
  src/main/java/asist/io/scheduled/TareasProgramadas.java
  src/main/java/asist/io/service/IAuthService.java
  src/main/java/asist/io/service/ICustomUserDetailsService.java
  src/main/java/asist/io/service/IEmailSenderService.java
  src/main/java/asist/io/service/ITokenService.java
  src/main/java/asist/io/service/IUsuarioService.java
  src/main/java/asist/io/service/impl/AuthServiceImp.java
  src/main/java/asist/io/service/impl/CustomUserDetailsServiceImp.java
  src/main/java/asist/io/service/impl/EmailSenderServiceImp.java
  src/main/java/asist/io/service/impl/TokenServiceImp.java
  src/main/java/asist/io/service/impl/UsuarioServiceImp.java
  src/main/java/asist/io/util/BodyGenerator.java
  src/main/resources/application.properties
  src/main/resources/banner.txt
  src/main/resources/log4j.properties
  src/test/java/asist/io/IAuthServiceTest.java
  src/test/java/asist/io/IEmailSenderServiceTest.java
  src/test/java/asist/io/ITokenServiceTest.java
  src/test/java/asist/io/IUsuarioServiceTest.java
Labels: enhancement, Security

#16 Se fixearon errores de seguridad en el proyecto
  src/main/java/asist/io/controller/AuthController.java
  src/main/java/asist/io/controller/UsuarioController.java
  src/main/java/asist/io/dto/passwordDTO/PasswordDTO.java
  src/main/java/asist/io/dto/usuarioDTO/UsuarioCambioContrasenaDTO.java
  src/main/java/asist/io/dto/usuarioDTO/UsuarioGetDTO.java
  src/main/java/asist/io/dto/usuarioDTO/UsuarioLoginDTO.java
  src/main/java/asist/io/dto/usuarioDTO/UsuarioLoginResDTO.java
  src/main/java/asist/io/dto/usuarioDTO/UsuarioRegDTO.java
  src/main/java/asist/io/dto/usuarioDtos/UsuarioRegDto.java
  src/main/java/asist/io/mapper/UsuarioMapper.java
  src/main/java/asist/io/service/IAuthService.java
  src/main/java/asist/io/service/IEmailSenderService.java
  src/main/java/asist/io/service/IUsuarioService.java
  src/main/java/asist/io/service/impl/AuthServiceImp.java
  src/main/java/asist/io/service/impl/EmailSenderServiceImp.java
  src/main/java/asist/io/service/impl/UsuarioServiceImp.java
  src/test/java/asist/io/IAuthServiceTest.java
  src/test/java/asist/io/IEmailSenderServiceTest.java
  src/test/java/asist/io/ITokenServiceTest.java
  src/test/java/asist/io/IUsuarioServiceTest.java
Labels: fix

#17 [FEATURE]: Añadir log4j en services
  src/main/java/asist/io/service/impl/CursoServiceImpl.java
  src/main/java/asist/io/service/impl/EstudianteServiceImpl.java
  src/main/java/asist/io/service/impl/InscripcionServiceImpl.java
Labels: enhancement

#21 [FEATURE]: Generar código de asistencia
  src/main/java/asist/io/controller/CursoController.java
  src/main/java/asist/io/service/ICursoService.java
  src/main/java/asist/io/service/impl/CursoServiceImpl.java
  src/test/java/asist/io/CursoServiceTest.java
Labels: enhancement

#22 Feature/service asistencia
  src/main/java/asist/io/controller/AuthController.java
  src/main/java/asist/io/controller/UsuarioController.java
  src/main/java/asist/io/dto/asistenciaDTO/AsistenciaGetDTO.java
  src/main/java/asist/io/dto/asistenciaDTO/AsistenciaPostDTO.java
  src/main/java/asist/io/dto/passwordDTO/PasswordDTO.java
  src/main/java/asist/io/dto/usuarioDTO/UsuarioLoginDTO.java
  src/main/java/asist/io/dto/usuarioDTO/UsuarioLoginResDTO.java
  src/main/java/asist/io/dto/usuarioDTO/UsuarioPostDTO.java
  src/main/java/asist/io/entity/Asistencia.java
  src/main/java/asist/io/entity/Estudiante.java
  src/main/java/asist/io/entity/Usuario.java
  src/main/java/asist/io/mapper/AsistenciaMapper.java
  src/main/java/asist/io/mapper/UsuarioMapper.java
  src/main/java/asist/io/repository/AsistenciaRepository.java
  src/main/java/asist/io/repository/InscripcionRepository.java
  src/main/java/asist/io/service/IAsistenciaService.java
  src/main/java/asist/io/service/ICursoService.java
  src/main/java/asist/io/service/IEstudianteService.java
  src/main/java/asist/io/service/IInscripcionService.java
  src/main/java/asist/io/service/IUsuarioService.java
  src/main/java/asist/io/service/impl/AsistenciaServiceImpl.java
  src/main/java/asist/io/service/impl/CursoServiceImpl.java
  src/main/java/asist/io/service/impl/EmailSenderServiceImpl.java
  src/main/java/asist/io/service/impl/EstudianteServiceImpl.java
  src/main/java/asist/io/service/impl/InscripcionServiceImpl.java
  src/main/java/asist/io/service/impl/TokenServiceImpl.java
  src/main/java/asist/io/service/impl/UsuarioServiceImpl.java
  src/main/java/asist/io/util/DateFormatter.java
  src/test/java/asist/io/AsistenciaTests.java
  src/test/java/asist/io/IAuthServiceTest.java
  src/test/java/asist/io/ITokenServiceTest.java
  src/test/java/asist/io/IUsuarioServiceTest.java
Labels: enhancement

#23 [FEATURE]: cors config
  src/main/java/asist/io/config/CorsConfig.java
Labels: enhancement

#24 [FIX]: Añadir referencia de id usuario a DTOs en curso service
  src/main/java/asist/io/dto/cursoDTO/CursoGetDTO.java
  src/main/java/asist/io/dto/cursoDTO/CursoPatchDTO.java
  src/main/java/asist/io/mapper/CursoMapper.java
  src/main/java/asist/io/service/impl/CursoServiceImpl.java
  src/test/java/asist/io/CursoServiceTest.java
Labels: fix

#27 [FIX]: tests estudiante inscripcion service
  src/test/java/asist/io/EstudianteServiceTest.java
  src/test/java/asist/io/InscripcionServiceTest.java
Labels: fix

#29 FEATURE/ Controllers horario-asistencia
  src/main/java/asist/io/controller/AsistenciaController.java
  src/main/java/asist/io/controller/AuthController.java
  src/main/java/asist/io/controller/HorarioController.java
  src/main/java/asist/io/dto/HorarioDTO/HorarioPatchDTO.java
  src/main/java/asist/io/dto/asistenciaDTO/AsistenciaGetDTO.java
  src/main/java/asist/io/dto/asistenciaDTO/AsistenciaPostDTO.java
  src/main/java/asist/io/mapper/AsistenciaMapper.java
  src/main/java/asist/io/repository/HorarioRepository.java
  src/main/java/asist/io/repository/TokenRepository.java
  src/main/java/asist/io/service/IAsistenciaService.java
  src/main/java/asist/io/service/IHorarioService.java
  src/main/java/asist/io/service/impl/AsistenciaServiceImpl.java
  src/main/java/asist/io/service/impl/EstudianteServiceImpl.java
  src/main/java/asist/io/service/impl/HorarioServiceImpl.java
  src/main/java/asist/io/util/DateFormatter.java
  src/main/resources/application.properties
  src/main/resources/import.sql
  src/test/java/asist/io/AsistenciaTest.java
Labels: enhancement

#30 Feature/informes pdf excel
  README.md
  src/main/java/asist/io/auth/SecurityConfig.java
  src/main/java/asist/io/controller/AsistenciaController.java
  src/main/java/asist/io/controller/AuthController.java
  src/main/java/asist/io/dto/HorarioDTO/HorarioPostDTO.java
  src/main/java/asist/io/entity/Token.java
  src/main/java/asist/io/service/IAsistenciaService.java
  src/main/java/asist/io/service/impl/AsistenciaServiceImpl.java
  src/main/java/asist/io/service/impl/HorarioServiceImpl.java
  src/main/java/asist/io/util/BodyGenerator.java
  src/main/java/asist/io/util/Constantes.java
  src/main/java/asist/io/util/ExcelGenerator.java
  src/main/resources/import.sql
Labels: enhancement

#31 fix/metodos-faltantes-usuario
  src/main/java/asist/io/controller/UsuarioController.java
  src/main/java/asist/io/dto/HorarioDTO/HorarioPostDTO.java
  src/main/java/asist/io/dto/usuarioDTO/UsuarioPatchDTO.java
  src/main/java/asist/io/entity/Asistencia.java
  src/main/java/asist/io/entity/Curso.java
  src/main/java/asist/io/entity/Horario.java
  src/main/java/asist/io/entity/Usuario.java
  src/main/java/asist/io/service/IUsuarioService.java
  src/main/java/asist/io/service/impl/UsuarioServiceImpl.java
  src/main/java/asist/io/util/Constantes.java
  src/test/java/asist/io/AsistenciaTest.java
  src/test/java/asist/io/CursoServiceTest.java
  src/test/java/asist/io/EstudianteServiceTest.java
  src/test/java/asist/io/HorarioTest.java
  src/test/java/asist/io/IAuthServiceTest.java
  src/test/java/asist/io/ITokenServiceTest.java
  src/test/java/asist/io/IUsuarioServiceTest.java
  src/test/java/asist/io/InscripcionServiceTest.java
Labels: enhancement
